In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix

archivo = '/content/drive/MyDrive/2do cuatrimestre/Aprendizaje automatico /set_de_datos/winequality-white.csv'
df = pd.read_csv(archivo, sep=';')
df['quality_label'] = df['quality'].apply(lambda x: 1 if x >= 7 else 0)
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,quality_label
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,0
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,0
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,0
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,0
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,0


In [ ]:
X = df.drop(columns=['quality', 'quality_label'])
y = df['quality_label']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)
X_val_train, X_val_test, y_val_train, y_val_test = train_test_split(X_train, y_train, test_size=0.2, random_state=123)


In [ ]:
#REGRESION LOGISTICA
for C in [0.01,0.1, 1, 10,100]:
    try:
        modelo = LogisticRegression(C=C, max_iter=3000,fit_intercept=True, random_state=123)
        modelo.fit(X_val_train, y_val_train)
        y_pred_val = modelo.predict(X_val_test)
        AC = accuracy_score(y_val_test, y_pred_val)
        F1 = f1_score(y_val_test, y_pred_val)
        CM = confusion_matrix(y_val_test, y_pred_val)
        print(f"\nC: {C}")
        print(f"Accuracy: {AC:.3f} | F1: {F1:.3f}")
    except Exception as e:
        print(f"Error con C={C}: {e}")


C: 0.01
Accuracy: 0.777 | F1: 0.242

C: 0.1
Accuracy: 0.788 | F1: 0.325

C: 1
Accuracy: 0.784 | F1: 0.347

C: 10
Accuracy: 0.784 | F1: 0.352

C: 100
Accuracy: 0.784 | F1: 0.352


In [ ]:
#ARBOL DE DECISIÓN
for d in range(2,21):
  modelo_arbol = DecisionTreeClassifier(max_depth=d, random_state=123)
  modelo_arbol.fit(X_val_train, y_val_train)
  y_pred= modelo_arbol.predict(X_val_test)
  AC = accuracy_score(y_val_test, y_pred)
  F1 = f1_score(y_val_test, y_pred)
  CM = confusion_matrix(y_val_test, y_pred)
  print(f"\nd: {d}")
  print(f"Accuracy: {AC:.3f} | F1: {F1:.3f}")


d: 2
Accuracy: 0.776 | F1: 0.273

d: 3
Accuracy: 0.769 | F1: 0.267

d: 4
Accuracy: 0.800 | F1: 0.457

d: 5
Accuracy: 0.807 | F1: 0.485

d: 6
Accuracy: 0.806 | F1: 0.469

d: 7
Accuracy: 0.788 | F1: 0.481

d: 8
Accuracy: 0.797 | F1: 0.457

d: 9
Accuracy: 0.792 | F1: 0.469

d: 10
Accuracy: 0.784 | F1: 0.480

d: 11
Accuracy: 0.802 | F1: 0.520

d: 12
Accuracy: 0.804 | F1: 0.544

d: 13
Accuracy: 0.797 | F1: 0.562

d: 14
Accuracy: 0.786 | F1: 0.536

d: 15
Accuracy: 0.801 | F1: 0.569

d: 16
Accuracy: 0.797 | F1: 0.569

d: 17
Accuracy: 0.792 | F1: 0.538

d: 18
Accuracy: 0.811 | F1: 0.591

d: 19
Accuracy: 0.807 | F1: 0.582

d: 20
Accuracy: 0.810 | F1: 0.587


In [ ]:
#MODELO KNN
for k in [5,10,15,20,25,30]:
  for peso in ['uniform', 'distance']:
    modelo_knn = KNeighborsClassifier(n_neighbors=k, weights=peso)
    modelo_knn.fit(X_val_train, y_val_train)
    y_pred = modelo_knn.predict(X_val_test)
    AC = accuracy_score(y_val_test, y_pred)
    F1 = f1_score(y_val_test, y_pred)
    CM = confusion_matrix(y_val_test, y_pred)



k: 5 | peso: uniform
Accuracy: 0.749 | F1: 0.332

k: 5 | peso: distance
Accuracy: 0.795 | F1: 0.495

k: 10 | peso: uniform
Accuracy: 0.765 | F1: 0.193

k: 10 | peso: distance
Accuracy: 0.812 | F1: 0.515

k: 15 | peso: uniform
Accuracy: 0.765 | F1: 0.227

k: 15 | peso: distance
Accuracy: 0.829 | F1: 0.518

k: 20 | peso: uniform
Accuracy: 0.763 | F1: 0.147

k: 20 | peso: distance
Accuracy: 0.830 | F1: 0.513

k: 25 | peso: uniform
Accuracy: 0.764 | F1: 0.140

k: 25 | peso: distance
Accuracy: 0.833 | F1: 0.509

k: 30 | peso: uniform
Accuracy: 0.767 | F1: 0.124

k: 30 | peso: distance
Accuracy: 0.830 | F1: 0.498


In [ ]:
mejor_regresion = LogisticRegression(C=10, max_iter=1000,fit_intercept=True, random_state=123)
mejor_regresion.fit(X_train, y_train)
y_pred_test = mejor_regresion.predict(X_test)
AC = accuracy_score(y_test, y_pred_test)
F1 = f1_score(y_test, y_pred_test)
CM = confusion_matrix(y_test, y_pred_test)
print("Mejor modelo regresion logistica")
print(f"Accuracy: {AC:.3f} | F1: {F1:.3f}")
print("Matriz de Confusión:")
print(CM)

Mejor modelo regresion logistica
Accuracy: 0.802 | F1: 0.382
Matriz de Confusión:
[[726  46]
 [148  60]]


In [ ]:
mejor_arbol = DecisionTreeClassifier(max_depth=18, random_state=123)
mejor_arbol.fit(X_train, y_train)
y_pred_test = mejor_arbol.predict(X_test)
AC = accuracy_score(y_test, y_pred_test)
F1 = f1_score(y_test, y_pred_test)
CM = confusion_matrix(y_test, y_pred_test)
print("Mejor modelo Arbol")
print(f"Accuracy: {AC:.3f} | F1: {F1:.3f}")
print("Matriz de Confusión:")
print(CM)

Mejor modelo Arbol
Accuracy: 0.829 | F1: 0.625
Matriz de Confusión:
[[672 100]
 [ 68 140]]


In [ ]:
mejor_knn = KNeighborsClassifier(n_neighbors=15, weights='distance')
mejor_knn.fit(X_train, y_train)
y_pred_test = mejor_knn.predict(X_test)
AC = accuracy_score(y_test, y_pred_test)
F1 = f1_score(y_test, y_pred_test)
CM = confusion_matrix(y_test, y_pred_test)
print("Mejor modelo KNN")
print(f"Accuracy: {AC:.3f} | F1: {F1:.3f}")
print("Matriz de Confusión:")
print(CM)

Mejor modelo KNN
Accuracy: 0.843 | F1: 0.552
Matriz de Confusión:
[[731  41]
 [113  95]]


In [ ]:
modelo_final = mejor_arbol
print('El modelo con el mejor rendimiento es: \n')
modelo_final.fit(X, y)

El modelo con el mejor rendimiento es: 



DecisionTreeClassifier(max_depth=18, random_state=123)